[package]
name = "generalizer"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.5.6"                                  # for pest parser
pest_derive = "2.5.6"
clap = {version="=3.2.22",features=["yaml"]}